"""initial tables

Revision ID: 436b2ba33e34
Revises: 
Create Date: 2026-04-19 19:57:37.559431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '436b2ba33e34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_lng', sa.Float(), nullable=False),
    sa.Column('zone_id', sa.String(length=100), nullable=True),
    sa.Column('stream_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'DEGRADED', name='camerastatus'), nullable=False),
    sa.Column('analytics_profile', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_profiles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.Enum('RELIGIOUS_PROCESSION', 'PRAYER_GATHERING', 'TRIBAL_GATHERING', 'EID_CELEBRATION', 'NORMAL', name='eventtype'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('affected_camera_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('threshold_overrides', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('suppressed_alert_types', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', name='eventstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('object_type', sa.Enum('PERSON', 'VEHICLE', 'BIKE', 'BAG', 'OTHER', name='objecttype'), nullable=False),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_ref', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('alert_type', sa.Enum('INTRUSION', 'LOITERING', 'CROWD', 'FIGHT', 'ABANDONED_OBJECT', 'TRAFFIC_VIOLATION', 'FIRE', 'WEAPON', 'FALL', 'UNKNOWN', name='alerttype'), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'DISMISSED', 'ESCALATED', name='alertstatus'), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plate_reads',
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.Column('plate_text', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vehicle_color', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plate_reads_plate_text'), 'plate_reads', ['plate_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plate_reads_plate_text'), table_name='plate_reads')
    op.drop_table('plate_reads')
    op.drop_table('alerts')
    op.drop_table('tracks')
    op.drop_table('event_profiles')
    op.drop_table('cameras')
    # ### end Alembic commands ###
